In [37]:
import numpy as np
import numpy
from numpy.random import MT19937
from numpy.random import RandomState, SeedSequence
import os
from pprint import pprint

In [3]:
f_in = "7eu7_P_res2.5_apix1_D256.cs"

In [4]:
cs_in = np.load(f_in)

In [5]:
cs_in

array([(11124602343295557556, b'J443/simulated_particles.mrcs',    0, [256, 256], 1., 1., 0, b'', 0, 300., 2.7, 0.07, 18617.574, 18851.084, 0.72282326, 0., 1., 0., [0., 0.], [0., 0.], [0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.], 0., 0, [0., 0.], [ 1.3463968 , -1.3463968 ,  0.44879895], 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0, 0., [0., 0., 0.], [0., 0.], [0., 0., 0.]),
       ( 4784037077488378550, b'J443/simulated_particles.mrcs',    1, [256, 256], 1., 1., 0, b'', 0, 300., 2.7, 0.07, 19029.355, 19329.691, 0.49533406, 0., 1., 0., [0., 0.], [0., 0.], [0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.], 0., 0, [0., 0.], [ 2.2439947 , -0.44879895,  3.1415927 ], 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0, 0., [0., 0., 0.], [0., 0.], [0., 0., 0.]),
       ( 5137873220141739227, b'J443/simulated_particles.mrcs',    2, [256, 256], 1., 1., 0, b'', 0, 300., 2.7, 0.07, 17068.236, 17170.06 , 0.4674732 , 0., 1., 0., [0., 0.], [0., 0.], [0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.]

In [6]:
len(cs_in[0])

45

In [7]:
type(cs_in)

numpy.ndarray

In [8]:
cs_in.dtype

dtype([('uid', '<u8'), ('blob/path', 'S30'), ('blob/idx', '<u4'), ('blob/shape', '<u4', (2,)), ('blob/psize_A', '<f4'), ('blob/sign', '<f4'), ('blob/import_sig', '<u8'), ('ctf/type', 'S1'), ('ctf/exp_group_id', '<u4'), ('ctf/accel_kv', '<f4'), ('ctf/cs_mm', '<f4'), ('ctf/amp_contrast', '<f4'), ('ctf/df1_A', '<f4'), ('ctf/df2_A', '<f4'), ('ctf/df_angle_rad', '<f4'), ('ctf/phase_shift_rad', '<f4'), ('ctf/scale', '<f4'), ('ctf/scale_const', '<f4'), ('ctf/shift_A', '<f4', (2,)), ('ctf/tilt_A', '<f4', (2,)), ('ctf/trefoil_A', '<f4', (2,)), ('ctf/tetra_A', '<f4', (4,)), ('ctf/anisomag', '<f4', (4,)), ('ctf/bfactor', '<f4'), ('alignments3D/split', '<u4'), ('alignments3D/shift', '<f4', (2,)), ('alignments3D/pose', '<f4', (3,)), ('alignments3D/psize_A', '<f4'), ('alignments3D/error', '<f4'), ('alignments3D/error_min', '<f4'), ('alignments3D/resid_pow', '<f4'), ('alignments3D/slice_pow', '<f4'), ('alignments3D/image_pow', '<f4'), ('alignments3D/cross_cor', '<f4'), ('alignments3D/alpha', '<f4'), 

In [40]:
pprint(cs_in.dtype.names)
print(len(cs_in.dtype.names))



('uid',
 'blob/path',
 'blob/idx',
 'blob/shape',
 'blob/psize_A',
 'blob/sign',
 'blob/import_sig',
 'ctf/type',
 'ctf/exp_group_id',
 'ctf/accel_kv',
 'ctf/cs_mm',
 'ctf/amp_contrast',
 'ctf/df1_A',
 'ctf/df2_A',
 'ctf/df_angle_rad',
 'ctf/phase_shift_rad',
 'ctf/scale',
 'ctf/scale_const',
 'ctf/shift_A',
 'ctf/tilt_A',
 'ctf/trefoil_A',
 'ctf/tetra_A',
 'ctf/anisomag',
 'ctf/bfactor',
 'alignments3D/split',
 'alignments3D/shift',
 'alignments3D/pose',
 'alignments3D/psize_A',
 'alignments3D/error',
 'alignments3D/error_min',
 'alignments3D/resid_pow',
 'alignments3D/slice_pow',
 'alignments3D/image_pow',
 'alignments3D/cross_cor',
 'alignments3D/alpha',
 'alignments3D/alpha_min',
 'alignments3D/weight',
 'alignments3D/pose_ess',
 'alignments3D/shift_ess',
 'alignments3D/class_posterior',
 'alignments3D/class',
 'alignments3D/class_ess',
 'alignments3D/localpose',
 'alignments3D/localshift',
 'alignments3D/localfulcrum')
45


In [44]:
cs_in["ctf/df1_A"][:3]

array([18617.574, 19029.355, 17068.236], dtype=float32)

In [45]:
cs_in["ctf/df2_A"][:3]

array([18851.084, 19329.691, 17170.06 ], dtype=float32)

In [41]:
cs_in["ctf/bfactor"]

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [10]:
cs_in.dtype["alignments3D/pose"]


dtype(('<f4', (3,)))

In [11]:
cs_in[0]["alignments3D/pose"]

array([ 1.3463968 , -1.3463968 ,  0.44879895], dtype=float32)

In [12]:
len(cs_in)

10000

In [13]:
cs_in.shape[0]

10000

In [14]:
cs_in[0]["alignments3D/pose"]

array([ 1.3463968 , -1.3463968 ,  0.44879895], dtype=float32)

In [15]:
# np.random.seed(None)
rs = RandomState(MT19937(SeedSequence(123456789)))
rs.normal(loc=0.0, scale=1.0, size=(3,))


array([-0.43411991, -0.47617187,  0.81874471])

In [16]:
# rs.get_state()

In [17]:
angles = np.concatenate([cs_in[i]["alignments3D/pose"] for i in range(cs_in.shape[0])])

In [18]:
angles.mean()

-0.011010533

In [19]:
angles.std()

1.7740637

In [20]:
x0 = 1


In [21]:
x0 += 1

In [22]:
x0

2

In [23]:
%pwd

'/Users/steven/repo/cemo/data/cryosparc/cs'

In [24]:
cs_in[:1]

array([(11124602343295557556, b'J443/simulated_particles.mrcs', 0, [256, 256], 1., 1., 0, b'', 0, 300., 2.7, 0.07, 18617.574, 18851.084, 0.72282326, 0., 1., 0., [0., 0.], [0., 0.], [0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.], 0., 0, [0., 0.], [ 1.3463968 , -1.3463968 ,  0.44879895], 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0, 0., [0., 0., 0.], [0., 0.], [0., 0., 0.])],
      dtype=[('uid', '<u8'), ('blob/path', 'S30'), ('blob/idx', '<u4'), ('blob/shape', '<u4', (2,)), ('blob/psize_A', '<f4'), ('blob/sign', '<f4'), ('blob/import_sig', '<u8'), ('ctf/type', 'S1'), ('ctf/exp_group_id', '<u4'), ('ctf/accel_kv', '<f4'), ('ctf/cs_mm', '<f4'), ('ctf/amp_contrast', '<f4'), ('ctf/df1_A', '<f4'), ('ctf/df2_A', '<f4'), ('ctf/df_angle_rad', '<f4'), ('ctf/phase_shift_rad', '<f4'), ('ctf/scale', '<f4'), ('ctf/scale_const', '<f4'), ('ctf/shift_A', '<f4', (2,)), ('ctf/tilt_A', '<f4', (2,)), ('ctf/trefoil_A', '<f4', (2,)), ('ctf/tetra_A', '<f4', (4,)), ('ctf/anisomag', '<f4', (4,)), ('ctf/bf

In [25]:
num_items = 10
f_out = f"test_cs_{num_items}_item.cs"
with open(f_out, "wb") as OUT:
    np.save(OUT, cs_in[:num_items])

In [26]:
%ls


7eu7_P_res2.5_apix1_D256.cs  test_cs_1_item.cs
check_cs.ipynb               test_cs_3_item.cs
test_cs_10_item.cs           two_snr1000_500.cs


In [27]:
x1 = np.load("test_cs_1_item.cs")

In [28]:
x1

array([(11124602343295557556, b'J443/simulated_particles.mrcs', 0, [256, 256], 1., 1., 0, b'', 0, 300., 2.7, 0.07, 18617.574, 18851.084, 0.72282326, 0., 1., 0., [0., 0.], [0., 0.], [0., 0.], [0., 0., 0., 0.], [0., 0., 0., 0.], 0., 0, [0., 0.], [ 1.3463968 , -1.3463968 ,  0.44879895], 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0, 0., [0., 0., 0.], [0., 0.], [0., 0., 0.])],
      dtype=[('uid', '<u8'), ('blob/path', 'S30'), ('blob/idx', '<u4'), ('blob/shape', '<u4', (2,)), ('blob/psize_A', '<f4'), ('blob/sign', '<f4'), ('blob/import_sig', '<u8'), ('ctf/type', 'S1'), ('ctf/exp_group_id', '<u4'), ('ctf/accel_kv', '<f4'), ('ctf/cs_mm', '<f4'), ('ctf/amp_contrast', '<f4'), ('ctf/df1_A', '<f4'), ('ctf/df2_A', '<f4'), ('ctf/df_angle_rad', '<f4'), ('ctf/phase_shift_rad', '<f4'), ('ctf/scale', '<f4'), ('ctf/scale_const', '<f4'), ('ctf/shift_A', '<f4', (2,)), ('ctf/tilt_A', '<f4', (2,)), ('ctf/trefoil_A', '<f4', (2,)), ('ctf/tetra_A', '<f4', (4,)), ('ctf/anisomag', '<f4', (4,)), ('ctf/bf

In [29]:
os.path.join(*[".."]*3)

'../../..'

In [30]:
shape = (10,)
dtype = [
        ('df1_A', '<f4'),
        ('df2_A', '<f4'),
        ('df_angle_rad', '<f4'),
        ('accel_kv', '<f4'),
        ('cs_mm', '<f4'),
        ('amp_contrast', '<f4'),
        ('phase_shift_rad', '<f4'),
    ]
ctf_params = numpy.recarray(shape, dtype=dtype)

In [31]:
ctf_params.shape

(10,)

In [32]:
ctf_params.dtype.names

('df1_A',
 'df2_A',
 'df_angle_rad',
 'accel_kv',
 'cs_mm',
 'amp_contrast',
 'phase_shift_rad')

In [33]:
ctf_params.dtype

dtype((numpy.record, [('df1_A', '<f4'), ('df2_A', '<f4'), ('df_angle_rad', '<f4'), ('accel_kv', '<f4'), ('cs_mm', '<f4'), ('amp_contrast', '<f4'), ('phase_shift_rad', '<f4')]))

In [34]:
len(ctf_params[0])

7

In [35]:
ctf_params.df1_A.shape

(10,)

In [36]:
type(list(ctf_params.dtype.names))

list